---
- set_fact:
    veracrypt_package: "veracrypt"
  when: veracrypt_gui

- name: Install VeraCrypt .deb package from the internet.
  apt:
    deb: "https://launchpad.net/veracrypt/trunk/{{ veracrypt_version }}-update{{ veracrypt_update }}/+download/{{ veracrypt_package }}-{{ veracrypt_version }}-Update{{ veracrypt_update }}-{{ ansible_distribution }}-{{ ansible_distribution_version }}-amd64.deb"

